definitions:
  dtos.ErrorResponse:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  entity.Task:
    properties:
      created_at:
        type: string
      description:
        type: string
      id:
        type: string
      is_completed:
        type: boolean
      title:
        type: string
      updated_at:
        type: string
    type: object
info:
  contact: {}
paths:
  /tasks/{id}:
    get:
      description: Get a task by its ID
      parameters:
      - description: Task ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Task'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
      summary: Get a task by ID
      tags:
      - tasks
swagger: "2.0"
