swagger: "2.0"
info:
  description: "API test code branch"
  version: "1.0.0"
  title: "API test code branch"
host: "localhost:8080"
basePath: "/"
schemes:
  - "http"
paths:
  /tasks/{id}:
    get:
      summary: "Return a task"
      parameters:
        - name: "id"
          in: "path"
          description: "ID of task to return"
          required: true
          type: "string"
      responses:
        200:
          description: "Successful response"
          schema:
            type: "object"
            properties:
              id:
                type: "string"
                example: "123e4567-e89b-12d3-a456-426614174000"
              title:
                type: "string"
                example: "Task Title"
              description:
                type: "string"
                example: "Task Description"
              is_completed:
                type: "boolean"
                example: false
              created_at:
                type: "string"
                format: "date-time"
                example: "2023-03-14T12:34:56Z"
              updated_at:
                type: "string"
                format: "date-time"
                example: "2023-03-14T12:34:56Z"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Task not found"
        500:
          description: "Internal server error"